### ISSUE TITLE
Reads every message

### ISSUE THREAD

**Issue by Unbloated** [Deltalizer/Discord-DM-Logitech-LCD#3]
Hi! I've used your plugin with my G15 keyboard and it seems if you have alot of DMs, it will show every detected message that has been sent.
![2024-05-09-21-06-50-249](https://github.com/JSDempsey/Discord-DM-Logitech-LCD/assets/106253650/72e73e5d-209c-4fb8-aa7f-0e018798bdc9)

Could you please fix that?
And- It is possible to make it so it shows the messages of a channel, and not only a DM?

**Comment by Kiesman** [comment]
Seconded, it's pulling every message from every channel, not just DMs.

**Comment by JSDempsey** [comment]
Hey guys, I don't have access to these keyboards anymore and don't have time to work on this anyway, if you want it fixed you'll have to make some changes yourself (the code is so old I'm surprised it even still works with discord)
